# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x03\x61pp\"4\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"$\n\x08TodoList\x12\x18\n\x05items\x18\x01 \x03(\x0b\x32\t.app.Todo\"\x1e\n\rCreatePayload\x12\r\n\x05title\x18\x01 \x01(\t\".\n\rTogglePayload\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"\x1b\n\rDeletePayload\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1f\n\rFilterPayload\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"G\n\nAppContext\x12\x18\n\x05items\x18\x01 \x03(\x0b\x32\t.app.Todo\x12\x0e\n\x06\x66ilter\x18\x02 \x01(\t\x12\x0f\n\x07next_id\x18\x03 \x01(\x05\"P\n\x0cMachineState\x12\r\n\x05state\x18\x01 \x01(\t\x12 \n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x0f.app.AppContext\x12\x0f\n\x07version\x18\x03 \x01(\x04\"E\n\x0cMachineEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x16\n\x0e\x63lient_version\x18\x03 \x01(\x04\"\x95\x01\n\x0bSyncMessage\x12%\n\x08snapshot\x18\x01 \x01(\x0b\x32\x11.app.MachineStateH\x00\x12\"\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x11.app.MachineEventH\x00\x12#\n\x06update\x18\x03 \x01(\x0b\x32\x11.app.MachineStateH\x00\x12\x0f\n\x05\x65rror\x18\x04 \x01(\tH\x00\x42\x05\n\x03msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TODO']._serialized_start=18
  _globals['_TODO']._serialized_end=70
  _globals['_TODOLIST']._serialized_start=72
  _globals['_TODOLIST']._serialized_end=108
  _globals['_CREATEPAYLOAD']._serialized_start=110
  _globals['_CREATEPAYLOAD']._serialized_end=140
  _globals['_TOGGLEPAYLOAD']._serialized_start=142
  _globals['_TOGGLEPAYLOAD']._serialized_end=188
  _globals['_DELETEPAYLOAD']._serialized_start=190
  _globals['_DELETEPAYLOAD']._serialized_end=217
  _globals['_FILTERPAYLOAD']._serialized_start=219
  _globals['_FILTERPAYLOAD']._serialized_end=250
  _globals['_APPCONTEXT']._serialized_start=252
  _globals['_APPCONTEXT']._serialized_end=323
  _globals['_MACHINESTATE']._serialized_start=325
  _globals['_MACHINESTATE']._serialized_end=405
  _globals['_MACHINEEVENT']._serialized_start=407
  _globals['_MACHINEEVENT']._serialized_end=476
  _globals['_SYNCMESSAGE']._serialized_start=479
  _globals['_SYNCMESSAGE']._serialized_end=628
# @@protoc_insertion_point(module_scope)
