# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\x12\x04todo\"H\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\x12\x12\n\ncreated_at\x18\x04 \x01(\x03\"%\n\x08TodoList\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo\"\"\n\x11\x43reateTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\"2\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tcompleted\x18\x02 \x01(\x08\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"=\n\tTodoStats\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x05\x12\x11\n\tcompleted\x18\x03 \x01(\x05\"\x9a\x01\n\x0b\x41piResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x04todo\x18\x03 \x01(\x0b\x32\n.todo.TodoH\x00\x12#\n\ttodo_list\x18\x04 \x01(\x0b\x32\x0e.todo.TodoListH\x00\x12 \n\x05stats\x18\x05 \x01(\x0b\x32\x0f.todo.TodoStatsH\x00\x42\x06\n\x04\x64\x61ta\"x\n\tTodoEvent\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.todo.EventType\x12\x18\n\x04todo\x18\x02 \x01(\x0b\x32\n.todo.Todo\x12\x12\n\ndeleted_id\x18\x03 \x01(\x05\x12\x1e\n\x05stats\x18\x04 \x01(\x0b\x32\x0f.todo.TodoStats*2\n\tEventType\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0b\n\x07UPDATED\x10\x01\x12\x0b\n\x07\x44\x45LETED\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=596
  _globals['_EVENTTYPE']._serialized_end=646
  _globals['_TODO']._serialized_start=20
  _globals['_TODO']._serialized_end=92
  _globals['_TODOLIST']._serialized_start=94
  _globals['_TODOLIST']._serialized_end=131
  _globals['_CREATETODOREQUEST']._serialized_start=133
  _globals['_CREATETODOREQUEST']._serialized_end=167
  _globals['_UPDATETODOREQUEST']._serialized_start=169
  _globals['_UPDATETODOREQUEST']._serialized_end=219
  _globals['_DELETETODOREQUEST']._serialized_start=221
  _globals['_DELETETODOREQUEST']._serialized_end=252
  _globals['_TODOSTATS']._serialized_start=254
  _globals['_TODOSTATS']._serialized_end=315
  _globals['_APIRESPONSE']._serialized_start=318
  _globals['_APIRESPONSE']._serialized_end=472
  _globals['_TODOEVENT']._serialized_start=474
  _globals['_TODOEVENT']._serialized_end=594
# @@protoc_insertion_point(module_scope)
